<a href="https://colab.research.google.com/github/Ashsam2310/Ashsam2310/blob/main/Intro_to_Tensorflow_%26_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==1.14

     |████████████████████████████████| 109.3 MB 52 kB/s 
     |████████████████████████████████| 50 kB 6.7 MB/s 
     |████████████████████████████████| 3.1 MB 39.0 MB/s 
     |████████████████████████████████| 488 kB 67.7 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.7.0
    Uninstalling tensorflow-estimator-2.7.0:
      Successfully uninstalled tensorflow-estimator-2.7.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.7.0
    Uninstalling tensorboard-2.7.0:
      Successfully uninstalled tensorboard-2.7.0
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.7.0
    Uninstalling tensorflow-2.7.0:
      Successfully uninstalled tensorflow-2.7.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
kapre 0.3.7 requires tensorflow>=2.0.0, but you

In [2]:
import tensorflow as tf

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

In [ ]:
hello_constant=tf.constant('Hello World')
hello_constant

<tf.Tensor 'Const:0' shape=() dtype=string>

In [ ]:
hello_constant=tf.constant('Hello World')
hello_constant
with tf.Session() as sess:
  output=sess.run(hello_constant)
  print(output)

b'Hello World'


In [ ]:
with tf.Graph().as_default():
  c1=tf.constant(4,dtype=tf.float64,name='c')
with tf.name_scope("prefix_name"):
  c2=tf.constant(4,dtype=tf.int32,name='c')
  c3=tf.constant(4,dtype=tf.float64,name='c')
  print(c1)
  print(c2)
  print(c3)

Tensor("c:0", shape=(), dtype=float64)
Tensor("prefix_name/c:0", shape=(), dtype=int32)
Tensor("prefix_name/c_1:0", shape=(), dtype=float64)


In [ ]:
print(c1.name)
print(c2.name)
print(c3.name)

c:0
prefix_name/c:0
prefix_name/c_1:0


In [ ]:
init_val=tf.random_normal((1,5),0,1)
var=tf.Variable(init_val,name='var')
print("pre run: \n{}".format(var))
init=tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  post_var=sess.run(var)
print(post_var)

pre run: 
<tf.Variable 'var:0' shape=(1, 5) dtype=float32_ref>
[[ 0.84187216 -0.04143564 -1.1756587   0.33135477  0.96608067]]


In [ ]:
import tensorflow as tf

In [ ]:
sess=tf.Session()
sess.run(hello_constant)

b'Hello World'

In [ ]:
x=tf.placeholder(tf.string)
sess=tf.Session()
op=sess.run(x,feed_dict={x:'test'})
print(op)

test


In [ ]:
x=tf.placeholder(tf.string)
y=tf.placeholder(tf.int32)

z=tf.placeholder(tf.float32)
sess=tf.Session()
op_x=sess.run(x,feed_dict={x:'test',y:123,z:45.67})
op_y=sess.run(y,feed_dict={x:'test',y:123,z:45.67})

print(op_x)
print(op_y)

test
123


In [ ]:
x=tf.placeholder("float",None)
y=x**2
result=sess.run(y,feed_dict={x:[1,2,3]})
print(result)

[1. 4. 9.]


In [ ]:
a=tf.subtract(10,4)

In [ ]:
b=tf.multiply(2,5)

In [ ]:
reslt=sess.run(a)
print(reslt)

6


In [ ]:
res=sess.run(a)
print(res)

6


In [ ]:
c=tf.subtract(tf.constant(4.0),tf.constant(1.0))
with tf.Session() as sess:
   res=sess.run(c)
   print(res)

3.0


In [ ]:
c=tf.subtract(tf.cast(tf.constant(4.0),tf.int32),tf.constant(1))
with tf.Session() as sess:
   res=sess.run(c)
   print(res)

3


In [ ]:
n_features=120
n_labels=5
weights=tf.Variable(tf.truncated_normal((n_features,n_labels)))

In [ ]:
weights

<tf.Variable 'Variable:0' shape=(120, 5) dtype=float32_ref>

In [ ]:
n_labels=5
bias=tf.Variable(tf.zeros(n_labels))

In [ ]:
a=tf.add(2,5)
b=tf.multiply(a,3)
sess=tf.Session()
replace={a:10}
reslt=sess.run(b,feed_dict=replace)
print(reslt)

30


In [ ]:
x=tf.nn.softmax([2.0,1.0,0.2])
wer=sess.run(x)
print(wer)

[0.65223986 0.23994564 0.10781453]


In [ ]:
x=tf.reduce_sum([1,2,3,4,5,6])
ot=sess.run(x)
print(ot)

21


In [ ]:
l=tf.log(100.0)
out=sess.run(l)
print(out)

4.6051702


In [ ]:
softmax_data=[0.7,0.2,0.1]
one_hot_data=[1.0,0.0,0.0]

softmax=tf.placeholder(tf.float32)
onehot=tf.placeholder(tf.float32)

cross_entropy=-tf.reduce_sum(tf.multiply(onehot,tf.log(softmax)))

sess=tf.Session()
op=sess.run(cross_entropy,feed_dict={onehot:one_hot_data,softmax:softmax_data})
print(op)

0.35667497


In [ ]:
tensor flow 1 has computational graphs which has nodes and edges..where edges are the data points and nodes are the operation.
Computational graph is then run inside a session.
in tensorflow 2 it has eager execution i.e. it can be executed without session.

MNIST USING TENSORFLOW

In [12]:
from __future__ import print_function
from tensorflow.examples.tutorials.mnist import input_data
mnist=input_data.read_data_sets("tmp/data/",one_hot=True)


Extracting tmp/data/train-images-idx3-ubyte.gz
Extracting tmp/data/train-labels-idx1-ubyte.gz
Extracting tmp/data/t10k-images-idx3-ubyte.gz
Extracting tmp/data/t10k-labels-idx1-ubyte.gz


In [4]:
mnist

Datasets(train=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7f6d89d0aa90>, validation=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7f6d80953e10>, test=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7f6d89dfc750>)

In [5]:
#parameters
learning_rate=0.1
num_steps=500
display_step=100
batch_size=120

#Network Parameters
n_hidden_1=256    #1st layer
n_hidden_2=256
num_input=784
num_classes=10

#tf Graph Input
X=tf.placeholder("float",[None,num_input])
Y=tf.placeholder("float",[None,num_classes])

In [6]:
# store layers weights and biases
weights={
    'h1':tf.Variable(tf.random_normal([num_input,n_hidden_1])),
    'h2':tf.Variable(tf.random_normal([n_hidden_1,n_hidden_2])),
    'out':tf.Variable(tf.random_normal([n_hidden_2,num_classes]))
}

biases={
    'b1':tf.Variable(tf.random_normal([n_hidden_1])),
    'b2':tf.Variable(tf.random_normal([n_hidden_2])),
    'out':tf.Variable(tf.random_normal([num_classes]))
}


In [7]:
def neural_net(x):
  layer_1=tf.add(tf.matmul(x,weights['h1']),biases['b1'])
  layer_2=tf.add(tf.matmul(layer_1,weights['h2']),biases['b2'])
  out_layer=tf.matmul(layer_2,weights['out'])+biases['out']
  return out_layer

In [8]:
#Construct Model
logits=neural_net(X)

#define loss and optimizer
loss_op=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,labels=Y))
optimizer=tf.train.AdamOptimizer(learning_rate=learning_rate)
train_op=optimizer.minimize(loss_op)

#evaluate model(with test logits,for dropout to be disabled)
correct_pred=tf.equal(tf.argmax(logits,1),tf.argmax(Y,1))
accuracy=tf.reduce_mean(tf.cast(correct_pred,tf.float32))

#initialize the variables(i.e. assign their default values)
init=tf.global_variables_initializer()

In [11]:
with tf.Session() as sess:
  sess.run(init)
  for step in range (1,num_steps+1):
    batch_x,batch_y=mnist.train.next_batch(batch_size)
    #run optimization op(backprop)
    sess.run(train_op,feed_dict={X:batch_x,Y:batch_y})
    if step% display_step==0 or step==1:
      #calculate batch loss and accuracy
      loss,acc=sess.run([loss_op,accuracy],feed_dict={X:batch_x,Y:batch_y})

      print("Step"+str(step)+",Minibatch Loss="+ \
            "{:.4f}".format(loss)+",Training Accuracy="+\
            "{:.3f}".format(acc))
      
  print("Optimization Finished")
  print("Testing Accuracy:",\
        sess.run(accuracy,feed_dict={X:mnist.test.images,Y:mnist.test.labels}))

Step1,Minibatch Loss=9435.2920,Training Accuracy=0.342
Step100,Minibatch Loss=158.0122,Training Accuracy=0.908
Step200,Minibatch Loss=92.9001,Training Accuracy=0.908
Step300,Minibatch Loss=101.3897,Training Accuracy=0.850
Step400,Minibatch Loss=96.9403,Training Accuracy=0.858
Step500,Minibatch Loss=62.4271,Training Accuracy=0.908
Optimization Finished
Testing Accuracy: 0.8734


In [10]:
sess.run(accuracy,feed_dict={X:mnist.test.images,Y:mnist.test.labels})

RuntimeError: ignored